### PR TITLE
[TSK-281] Changes in file saving and Input Parameter

### PR DESCRIPTION
**Pull request by iamMihirT**
- For saving the tweets I have utilized the username which is available from the tweets scraped. Plus I have added uuid incase the username are same and consecutive. For timeframe since we are only getting dates they wont be helpful so I have used local time at which the tweets are scraped to further distinct them after saving.
- In twitter while scraping we could actually use any query and start/end dates while using CLI. 
example:- 
python twitter_api_scraper.py --query "Hurricane" --start_date "2024-01-01" --end_date "2024-01-31".
For running it using server.py, I have added the new POST endpoint for inputing query, start date and end date. 
Now the hardcoded parameters are on the augmentation part where currently its using Wildfire as default even when there is different query. @sk-ram can you take a look on how you can modify augmentation part of code.

### CODE REVIEW

**Comment by maany** [comment]
@sk-ram could you undo your changes here and move them to a separate PR for #9

**Comment by maany** [comment]
@sk-ram the only thing we care about is unique filenames for v2 ;) The usecase is going to be just the wildfires one, but we can inject a hardcoded value from the pipelines directly if that is easier.

**Comment by maany** [comment]
@iamMihirT @sk-ram can you make sure that this PR is only fixing the file naming scheme. Remove any other changes and send a separate PR. I want to release this in 2.0 milestone which will go live on Wednesday. Thanks!

**Comment by ghost** [comment]
@alebg, could you review this pull request?

**Comment by ghost** [comment]
@alebg, could you review this pull request?

**Comment by ghost** [comment]
@ydamit, could you please review it?

**Comment by maany** [comment]
Closing in favor of #10

**Pull request closed without merging**
